### ISSUE TITLE
Support more (squeak) menu commands

### ISSUE THREAD

**Issue by FranzSw** [hpi-swa-teaching/Algernon-Launcher#175]
As a user I want to find as many commands as possible in Algernon in order to not click through menus

## Acceptance Criteria
- [x] Make all top-level menu bar items accessible in Algernon
- [x] don't forget to test

**Comment by LinqLover** [comment]
Sorry if I'm disturbing your issue organization, but because I have been wishing for such a feature for like an eternity, I'd love to add my 2 cents to this feature request (probably these ideas might fit even better into one or multiple new issues):

Instead of only adding the items from the main docking menu bar to the launcher, you could go one step further and also integrate all actions and menu items from as many sources as possible - including the yellow-button (context) menu of the current morph, the menu items of the current window menu (![image](https://user-images.githubusercontent.com/38782922/116793622-0a6c8f80-aac8-11eb-9dbc-13835efc2e73.png)), and probably even menus from adjacent morphs. For example, this could empower you to do things such as:

- in a workspace, select a string, press <kbd>Alt</kbd> + <kbd>Space</kbd>, and search for "methods source with it" (this menu item is available via yellow-button menu > more)
- in a browser when the code pane is focused, press <kbd>Alt</kbd> + <kbd>Space</kbd>, and search for "assignments" (this menu item is available via the yellow-button menu on the class list)

In the light of a keyboard-oriented workflow, I think such a feature would be a great opportunity for this awesome tool. By the way, this proposal is strongly inspired by the Command Palette in VS Code (check it out if you didn't yet!). If you like this idea and have any further questions, please feel free to reply! 🙏

**Comment by bewee** [comment]
I think that the following features should become new issues? Or is any of these still part of this issue?

- Add menu-specific icons: Currently, all results of WorldMenuType share the world menu icon. Providing different icons for different kinds (->menus) of WorldMenuType result items would help to identify the meaning of results (e.g. Transcript app vs Transcript window). Problem is, the Type architecture currently doesn't support something like this
- Making submenu entries accessible (through tab actions). Currently, they are listed as executable results, but they aren't.
- Disabled menu entries should not appear as results
