### ISSUE TITLE
Deduplication of world menu entries

### ISSUE THREAD

**Issue by TheGrayStone** [hpi-swa-teaching/Algernon-Launcher#186]
As a confused user of Algernon, I want to only get one result for any given behavior caused by clicking a menu entry in order to have a less crowded result list.

## Example
When searching for 'Monticello Browser', one finds two world menu type results, both opening the monticello browser (one is an app, one a tool)

## Acceptance criteria
- [x] Don't list apps that already exist as tools

**Comment by bewee** [comment]
@FranzSw and I have talked a bit about this, and concluded that whenever there are a static and a dynamic item with the same name, we should go for deleting the dynamic item (because when we would delete the static item, and when the dynamic one is then removed later, we would have no more result at all)
